stages:
  - build
  - test

after_script:  
   - cd $CI_PROJECT_DIR
   - sudo ./ci/cleanup.sh

build:
  tags:
    - sm_ci
  stage: build
  script:
    - echo "-------   Start Build   -------"
    - /usr/local/go/bin/go build

test:
  tags:
    - sm_ci
  stage: test
  script:
    - sudo systemctl start rabbitmq-server.service
    - sudo iptables -t nat -A POSTROUTING -o ens3 -s 172.19.0.0/24 -j MASQUERADE
    - sudo cp ./ci/crt.pem  /etc/ssl/certs/
    - echo "-------   Run Unit tests   -------"
    - sudo -E /usr/local/go/bin/go test $(/usr/local/go/bin/go list ./... | grep -v "/vendor\|identification/visidentifier\|monitoring") -v -coverprofile .testCoverage.txt
    - /usr/local/go/bin/go tool cover -func=.testCoverage.txt
    - sudo rm .testCoverage.txt
    - sudo systemctl stop rabbitmq-server.service --no-block

