[[constraint]]
  name = "github.com/anexia-it/fsquota"
  version = "0.1.3"

[[constraint]]
  name = "github.com/cavaliercoder/grab"
  version = "2.0.0"

[[constraint]]
  name = "github.com/coreos/go-iptables"
  version = "0.4.5"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "21.0.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"

[[constraint]]
  name = "github.com/godbus/dbus"
  version = "5.0.2"

[[constraint]]
  name = "github.com/google/uuid"
  version = "1.1.1"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/jlaffaye/ftp"

[[constraint]]
  name = "github.com/mattn/go-sqlite3"
  version = "2.0.2"

[[constraint]]
  name = "github.com/opencontainers/runtime-spec"
  version = "1.0.1"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.19.11"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  branch = "master"
  name = "gitpct.epam.com/epmd-aepr/aos_common"
  source = "git@gitpct.epam.com:epmd-aepr/aos_common.git"
  
[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"
